herbstluftwm_focus_mode: improve script

diff --git a/herbstluftwm/bin/herbstluftwm_focus_mode b/herbstluftwm/bin/herbstluftwm_focus_mode
--- a/herbstluftwm/bin/herbstluftwm_focus_mode
+++ b/herbstluftwm/bin/herbstluftwm_focus_mode
@@ -17,9 +17,43 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.	If not, see <http://www.gnu.org/licenses/>.
 
+command -v polybar > /dev/null || { echo "ERROR: no polybar available"; exit 1; }
+
+# We use this method instead of 'herbstclient set' because it gives us
+# the preferred value of the configuration.
+_get_value ()
+{
+    local autostart
+    autostart="$HOME/.config/herbstluftwm/autostart"
+
+    sed "/$1/!d ; s,.* $1 \([a-z0-9]*\).*,\1," "$autostart"
+}
+
+smart_window_surroundings="$(_get_value smart_window_surroundings)"
+smart_frame_surroundings="$(_get_value smart_frame_surroundings)"
+frame_border_width="$(_get_value frame_border_width)"
+
+# This is used by the 'delight' script.
+focus_mode_status="$HOME"/.config/herbstluftwm/herbstluftwm_focus_mode_status
+
+_hc ()
+{
+    herbstclient "$@"
+}
+
 if pgrep -x polybar
 then
-    pkill -x polybar
+    _hc set smart_window_surroundings on
+    _hc set smart_frame_surroundings on
+    _hc set frame_border_width 0
+
+    echo "on" > "$focus_mode_status"
 else
+    _hc set smart_window_surroundings "$smart_window_surroundings"
+    _hc set smart_frame_surroundings "$smart_frame_surroundings"
+    _hc set frame_border_width "$frame_border_width"
+
+    echo "off" > "$focus_mode_status"
+
     polybar herbstluftwm &
 fi
