FULL REWRITE AND REVIEW: dynamic desktops
1. Rewrite bspwm_dynamic_desktops.  It is now better overall and has
   more options:
       --na|--send-all-to-desktop
       --ns|--send-focused-to-desktop
       --nm|--send-focused-to-next-monitor
       --da|--activate-desktop-and-place-receptacle
       --df|--focus-desktop
2. Adapt bspwm_multifaceted_operation.  Uses the long form of --na.
3. Full review sxhkdrc_bspc, since many things changed because of ^1.

diff --git a/bin/bin/bspwm_dynamic_desktops b/bin/bin/bspwm_dynamic_desktops
--- a/bin/bin/bspwm_dynamic_desktops
+++ b/bin/bin/bspwm_dynamic_desktops
@@ -21,34 +21,19 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 
-# WORK IN PROGRESS:  This script works as intended in my custom desktop
-# session, but still requires some extra work.  See the TODOs.
+# See the --options below for the available arguments for $1.  $2 must
+# be a number from 0 to 9.
+[ "$#" -eq 2 ] || { echo 'Must be run with two arguments.'; exit 1; }
 
+# Capture the arguments.  We need to run tests against them.  Renaming
+# them makes things easier to read.
+option="${@:1:1}"
+target_desktop="${@:2:1}"
 
-# Requires at least one argument.
-# TODO one or two args!
-[ "$#" -ge 1 ] || { echo 'Must run with one or two arguments.'; exit 1; }
-
-# Capture the argument{,s}.
-case "$#" in
-	2)
-		sel="$1"
-		num="$2"
-		;;
-	1)
-		num="$1"
-		;;
-esac
-
-# Make sure the $num is a valid number for desktop names.  This assumes
-# that we call the current script from within the hotkey daemon which
-# passes this: '^{0-9}'
-case "$num" in
-	\^[0-9])
-		target_desktop="${num:1}" # strips the leading caret (see the sxhkd config)
-		;;
-	*)
-		echo 'Target desktop must be 0 through 9'; exit 1;
+case "$target_desktop" in
+	[!0-9])
+		echo "The second argument must be a valid number"
+		exit 1
 		;;
 esac
 
@@ -63,32 +48,89 @@ _query_desktops() {
 #
 # If the target desktop does not exist, it is created on the spot.
 _desk_or_node() {
-	if ! _query_desktops "$target_desktop" > /dev/null; then
-		bspc monitor -a "$target_desktop" && bspc "$@"
-	else
-		bspc "$@"
-	fi
+	_dynamic_desktops() {
+		# Here we make sure we clean up the arguments passed to this
+		# function.  Then we can operate on them with greater
+		# flexibility.
+		local monitor action
+		monitor="${@:1:1}"
+		action="${@:2}"
+
+		# Leave the unquoted in tact!  Else the commands will not run.
+		if ! _query_desktops "$target_desktop" > /dev/null; then
+			bspc monitor "$monitor" -a "$target_desktop" && $action
+		else
+			# BACK-AND-FORTH behaviour:  inputting the number of the
+			# focused desktop switches to the last one.
+			#
+			# If you do not like this, just replace the whole if/fi part
+			# below with $action (and do not quote it).
+			if [ "$(_query_desktops --names)" -eq "$target_desktop" ]; then
+				bspc desktop -f last
+			else
+				$action
+			fi
+		fi
+	}
+
+	# Reorder desktops on the target monitor (the target is the first
+	# argument passed to this function.  The default is the focused one.
+	_desk_order() {
+		while read -r line; do
+			printf "%s\\n" "$line"
+		done < <(bspc query -D -m "${1:-focused}" --names) | sort -g | paste -d ' ' -s
+	}
+
+	# Determines whether the behaviour of this function concerns nodes
+	# or desktops.  The "monitor" is just a filter for nodes/desktops,
+	# hence the "shift".  It concerns multihead setups.
+	case "$1" in
+		node|desktop)
+			_dynamic_desktops 'focused.focused' bspc "$@"
+			bspc monitor -o $(eval _desk_order) # do not quote! we want term splitting here
+			;;
+		monitor)
+			shift
+			_dynamic_desktops next bspc "$@"
+			bspc monitor next -o $(eval _desk_order next) # do not quote! we want term splitting here
+			;;
+	esac
 }
 
 # Invoke the above command, passing to it arguments that change its
 # behaviour (desktop or node).
 #
-# TODO send node to unfocused monitor.
-case "$#" in
-	2)_desk_or_node node "${sel:-focused}" -d "$target_desktop";;
-	1)_desk_or_node desktop -f "$target_desktop";;
+# Mnemonics for shorter options:
+# n* == node
+# d* == desktop
+#
+# TODO LOWPRIORITY --no|--send-all-to-desktop-next-monitor*)
+# TODO to be implemented in bspwm_multifaceted_operations and sxhkd
+case "$option" in
+	--na|--send-all-to-desktop)
+		_desk_or_node node 'any.local' -d "${target_desktop}"
+		;;
+	--ns|--send-focused-to-desktop)
+		_desk_or_node node focused -d "${target_desktop}"
+		;;
+	--nm|--send-focused-to-next-monitor)
+		_desk_or_node monitor node focused -d "${target_desktop}"
+		;;
+	--da|--activate-desktop-and-place-receptacle)
+		_desk_or_node monitor node @"$target_desktop":/ -i && bspc desktop -a "${target_desktop}"
+		;;
+	--df|--focus-desktop)
+		_desk_or_node desktop -f "${target_desktop}"
+		;;
+	*)
+		echo "< $option > is not a valid option."
+		exit 1
+		;;
 esac
 
 # Remove empty desktops.  This works for multiple monitors, as well.
+# This will NOT REMOVE empty desktops that contain only receptacles
+# (applies to the --activate-desktop option above).
 for i in $(_query_desktops '.!focused.!occupied' --names); do
 	bspc desktop "$i" -r
 done
-
-# Reorder desktops on the focused monitor.
-_desk_order() {
-	while read -r line; do
-		printf "%s\\n" "$line"
-	done < <(bspc query -D -m focused --names) | sort -g | paste -d ' ' -s
-}
-
-bspc monitor -o $(_desk_order) # do not quote! we want term splitting here
