Several refinements to dynamic+dedicated desktops
The script now provides a more robust way of specifying dedicated
desktops and for doing so on more that one monitors.

diff --git a/bin/bin/bspwm_dynamic_desktops b/bin/bin/bspwm_dynamic_desktops
--- a/bin/bin/bspwm_dynamic_desktops
+++ b/bin/bin/bspwm_dynamic_desktops
@@ -50,33 +50,40 @@ option="${@:1:1}"
 target_desktop="${@:2:1}"
 
 case "$target_desktop" in
-	[!0-9])
-		echo "The second argument must be a valid number"
-		exit 1
-		;;
-    # The following switch allows us to specify a range of numbered
-    # desktops that we would always want to place on a dedicated
-    # monitor, which is here defined as the first on the list.
-    #
-    # THIS IS JUST A PROOF-OF-CONCEPT.  It only applies to the `--ns*'
-    # options (see the last part of the script).  As such, you can still
-    # send a node to any dynamically-created numbered desktop on the
-    # next monitor, by using the `--nm*' options.
-    #
-    # In principle, it is possible to have multiple dedicated monitors,
-    # but I feel that the current implementation already points at a
-    # possible approach to tackling that issue.
-    #
-    # Furthermore, we can target a monitor by its name (e.g. LVDS-1).
-    [1-4])
-        dedicated_desktops=1
-        dedicated_monitor="$(bspc query -M | sed 1q)" # Selects the 1st
+    [!0-9])
+        echo "The second argument must be a valid number"
+        exit 1
         ;;
 esac
 
+# The `dynamic_but_dedicated' switch allows us to specify a range of
+# numbered desktops that we would always want to place on dedicated
+# monitors.  This means that while we retain the functionality of
+# dynamically creating/removing desktops, we also bind certain desktops
+# to monitors.
+#
+# THIS IS JUST A PROOF-OF-CONCEPT.  It only applies to the `--ns*'
+# options (see the last part of the script).  As such, you can still
+# send a node to any dynamically-created numbered desktop on the
+# next monitor, by using the `--nm*' options.
+
+# Switch to `false' to restore the monitor-independent behaviour.
+dynamic_but_dedicated='true'
+
+# Here we specify the range of desktops that should always appear on the
+# monitor named `LVDS-1'.  Everything else appears on `VGA-1'.  You can
+# find the names of your monitors with `bspc query -M --names`.
+if [ "$dynamic_but_dedicated" = 'true' ]; then
+    dedicated_desktops='true'
+    case "$target_desktop" in
+        [1-5]) dedicated_monitor="LVDS-1" ;;
+        *)     dedicated_monitor="VGA-1"  ;;
+    esac
+fi
+
 # Command for querying BSPWM desktops.
 _query_desktops() {
-	bspc query -D -d "$@"
+    bspc query -D -d "$@"
 }
 
 # The core functionality of this script.  Behaviour changes based on
@@ -85,61 +92,61 @@ _query_desktops() {
 #
 # If the target desktop does not exist, it is created on the spot.
 _desk_or_node() {
-	_dynamic_desktops() {
-		# Here we make sure we clean up the arguments passed to this
-		# function.  Then we can operate on them with greater
-		# flexibility.
-		local monitor action
-		monitor="${@:1:1}"
-		action="${@:2}"
+    _dynamic_desktops() {
+        # Here we make sure we clean up the arguments passed to this
+        # function.      Then we can operate on them with greater
+        # flexibility.
+        local monitor action
+        monitor="${@:1:1}"
+        action="${@:2}"
 
-		# Leave the unquoted in tact!  Else the commands will not run.
-		if ! _query_desktops "$target_desktop" > /dev/null; then
-			bspc monitor "$monitor" -a "$target_desktop" && $action
-		else
-			# BACK-AND-FORTH behaviour:  inputting the number of the
-			# focused desktop switches to the last one.
-			#
-			# If you do not like this, just replace the whole if/fi part
-			# below with $action (and do not quote it).
-			if [ "$(_query_desktops --names)" -eq "$target_desktop" ]; then
-				bspc desktop -f last
-			else
-				$action
-			fi
-		fi
-	}
+        # Leave the unquoted in tact!  Else the commands will not run.
+        if ! _query_desktops "$target_desktop" > /dev/null; then
+            bspc monitor "$monitor" -a "$target_desktop" && $action
+        else
+            # BACK-AND-FORTH behaviour:      inputting the number of the
+            # focused desktop switches to the last one.
+            #
+            # If you do not like this, just replace the whole if/fi part
+            # below with $action (and do not quote it).
+            if [ "$(_query_desktops --names)" -eq "$target_desktop" ]; then
+                bspc desktop -f last
+            else
+                $action
+            fi
+        fi
+    }
 
-	# Reorder desktops on the target monitor (the target is the first
-	# argument passed to this function).  The default is the focused
-	# one.
-	_desk_order() {
-		while read -r line; do
-			printf "%s\\n" "$line"
-		done < <(bspc query -D -m "${1:-focused}" --names) | sort -g | paste -d ' ' -s
-	}
+    # Reorder desktops on the target monitor (the target is the first
+    # argument passed to this function).  The default is the focused
+    # one.
+    _desk_order() {
+        while read -r line; do
+            printf "%s\\n" "$line"
+        done < <(bspc query -D -m "${1:-focused}" --names) | sort -g | paste -d ' ' -s
+    }
 
-	# Determines whether the behaviour of this function concerns nodes
-	# or desktops.  The "monitor" is just a filter for nodes/desktops,
-	# hence the "shift".  It concerns multihead setups.
-	case "$1" in
-		node|desktop)
-			_dynamic_desktops 'focused.focused' bspc "$@"
-			bspc monitor -o $(eval _desk_order) # do not quote! we want term splitting here
-			;;
-		monitor)
-			shift
+    # Determines whether the behaviour of this function concerns nodes
+    # or desktops.  The "monitor" is just a filter for nodes/desktops,
+    # hence the "shift".  It concerns multihead setups.
+    case "$1" in
+        node|desktop)
+            _dynamic_desktops 'focused.focused' bspc "$@"
+            bspc monitor -o $(eval _desk_order) # do not quote! we want term splitting here
+            ;;
+        monitor)
+            shift
             if [ -n "$dedicated_desktops" ]; then
-			    _dynamic_desktops "$dedicated_monitor" bspc "$@"
-			    bspc monitor "$dedicated_monitor" -o $(eval _desk_order "$dedicated_monitor")
+                _dynamic_desktops "$dedicated_monitor" bspc "$@"
+                bspc monitor "$dedicated_monitor" -o $(eval _desk_order "$dedicated_monitor")
                 # do not quote the above $(…), as we want term splitting there
             else
-			    _dynamic_desktops next bspc "$@"
-			    bspc monitor next -o $(eval _desk_order next)
+                _dynamic_desktops next bspc "$@"
+                bspc monitor next -o $(eval _desk_order next)
                 # do not quote the above $(…), as we want term splitting there
             fi
-			;;
-	esac
+            ;;
+    esac
 }
 
 # Invoke the above command, passing to it arguments that change its
@@ -152,48 +159,48 @@ _desk_or_node() {
 # TODO LOWPRIORITY --no|--send-all-to-desktop-next-monitor*)
 # TODO to be implemented in bspwm_multifaceted_operations and sxhkd
 case "$option" in
-	--na|--send-all-to-desktop)
-		_desk_or_node node 'any.local' -d "${target_desktop}"
-		;;
-	--ns|--send-focused-to-desktop)
+    --na|--send-all-to-desktop)
+        _desk_or_node node 'any.local' -d "${target_desktop}"
+        ;;
+    --ns|--send-focused-to-desktop)
         if [ -n "$dedicated_desktops" ]; then
             _desk_or_node monitor node focused -d "${target_desktop}"
         else
-		    _desk_or_node node focused -d "${target_desktop}"
+            _desk_or_node node focused -d "${target_desktop}"
         fi
-		;;
-	--nsf|--send-focused-to-desktop-and-follow)
+        ;;
+    --nsf|--send-focused-to-desktop-and-follow)
         if [ -n "$dedicated_desktops" ]; then
             _desk_or_node monitor node focused -d "${target_desktop}" --follow
         else
-		    _desk_or_node node focused -d "${target_desktop}" --follow
+            _desk_or_node node focused -d "${target_desktop}" --follow
         fi
-		;;
-	--nm|--send-focused-to-next-monitor)
-		_desk_or_node monitor node focused -d "${target_desktop}"
-		;;
-	--nmf|--send-focused-to-next-monitor-and-follow)
-		_desk_or_node monitor node focused -d "${target_desktop}" --follow
-		;;
-	--da|--activate-desktop-and-place-receptacle)
-		_desk_or_node monitor node @"$target_desktop":/ -i && bspc desktop -a "${target_desktop}"
-		;;
-	--df|--focus-desktop)
+        ;;
+    --nm|--send-focused-to-next-monitor)
+        _desk_or_node monitor node focused -d "${target_desktop}"
+        ;;
+    --nmf|--send-focused-to-next-monitor-and-follow)
+        _desk_or_node monitor node focused -d "${target_desktop}" --follow
+        ;;
+    --da|--activate-desktop-and-place-receptacle)
+        _desk_or_node monitor node @"$target_desktop":/ -i && bspc desktop -a "${target_desktop}"
+        ;;
+    --df|--focus-desktop)
         if [ -n "$dedicated_desktops" ]; then
-		    _desk_or_node monitor desktop -f "${target_desktop}"
+            _desk_or_node monitor desktop -f "${target_desktop}"
         else
             _desk_or_node desktop -f "${target_desktop}"
         fi
-		;;
-	*)
-		echo "< $option > is not a valid option."
-		exit 1
-		;;
+        ;;
+    *)
+        echo "< $option > is not a valid option."
+        exit 1
+        ;;
 esac
 
 # Remove empty desktops.  This works for multiple monitors, as well.
 # This will NOT REMOVE empty desktops that contain only receptacles
 # (applies to the --activate-desktop option above).
 for i in $(_query_desktops '.!focused.!occupied' --names); do
-	bspc desktop "$i" -r
+    bspc desktop "$i" -r
 done
