Integrate dotsmenu
Rewrite the dotsmenu script.  The original concept of quickly accessing
dotfiles remains the same, but the code is written anew.

A key chord is now added to sxhkdrc to invoke dotsmenu directly.

If the script is run from within a terminal, it will open the selected
file in the $EDITOR.  Otherwise it will resort to using (in sequence):
$VISUAL, gvim, xdg-open.

diff --git a/bin/bin/dotsmenu b/bin/bin/dotsmenu
--- a/bin/bin/dotsmenu
+++ b/bin/bin/dotsmenu
@@ -1,8 +1,5 @@
 #!/bin/bash
 
-# DEPRECATED as of 2018-10-25 but kept for reference.  The corresponding
-# directory in my dotfiles has been removed.
-
     # This program is free software: you can redistribute it and/or modify
     # it under the terms of the GNU General Public License as published by
     # the Free Software Foundation, either version 3 of the License, or
@@ -16,47 +13,72 @@
     # You should have received a copy of the GNU General Public License
     # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# A dmenu script to edit predefined files.
-# Opens an editor to the file path.
-# This implementation works with dotfiles. Could be arbitrary files.
+# Dotsmenu: a dmenu script to edit configuration files that are stored
+# in a "dotfiles" directory of arbitrary depth.  Opens a new terminal
+# running the EDITOR on the selected file.  This script is part of my
+# dotfiles: https://gitlab.com/protesilaos/dotfiles.
+#
+# Debian Buster dependencies:
+# 	apt install suckless-tools fd-find
+#
+# TODO improve documentation
+# TODO review code
+# TODO add feedback messages
 
-# The full paths are manually included in a plain text file.
-# One path per line, starting with the 'label' we want to display in the menu.
-# Examples: 
-# Bspwm /home/USERNAME/.config/bspwm/bspwmrc
-# Tmux Keybindings /home/USERNAME/.tmux/keybindings.conf
+# NOTE this would not work with the Xresources, Xdefaults, etc., though
+# I do not use them…
+if [ -d "$HOME/dotfiles" ]; then
+	my_dots="$HOME/dotfiles"
+else
+	echo "ERROR"
+	echo "Your dotfiles are not available"
+	echo "Aborting"
+	exit 1
+fi
 
-# XXX NOTE this is a working demo that is tailored to my custom setup
-# PREREQUISITES
-# All of my dotfiles (stow everything)
-# https://gitlab.com/protesilaos/dotfiles
-
-# path to dotfiles index
-mydotsindex="$HOME/.mydotsindex"
-
-# define length of dotfiles' list (for use in dmenu -l)
-mydotsindex_length=$(cat $mydotsindex | wc -l)
-
-# gets the list with the file paths
-# keeps only the first part which is the path's label
-# that keeps the dmenu interface clean
-mydotsindex_selection_clean ()
-{
-    # pass custom colours to dmenu command
-    source $HOME/.local/share/my_colours/active-tempus-theme.sh
-
-    # get the system-wide custom font
-    source $HOME/.local/share/my_custom_ui_font.sh
-
-    sed -e 's,\(^[A-Za-z ]*\) \([a-z/._]*\),\1,g' $mydotsindex | \
-    dmenu -i -l $mydotsindex_length -p 'Edit dotfile' -nb $background -nf $foreground -sb $color1 -sf $background -fn "$my_custom_ui_font"
+my_configs() {
+	fdfind -H -t f '.*rc$|.*\.conf|config$' "$my_dots" | \
+	sed "s,$my_dots/,,g"
 }
 
-# capture dmenu output
-# match choice to the file path it references, exluding the label
-mydotsindex_choice=$(grep -w "$(mydotsindex_selection_clean) " .mydotsindex | sed -e 's,\([A-Za-z ]*\) \([A-Za-z/._ ]*\),\2,g')
+# Custom dmenu command.  Accepts the line height as an argument.
+my_dmenu() {
+	# Pass custom colours to dmenu command
+	source "$HOME/.local/share/my_colours/active-tempus-theme.sh"
 
-# open visual editor with path to selection
-if [ "$mydotsindex_choice" ]; then
-    $VISUAL "$mydotsindex_choice"
+	# Get the system-wide custom font, for use in dmenu
+	source "$HOME/.local/share/my_custom_ui_font.sh"
+
+	if [ -n "$1" ]; then
+		local height="$1"
+	else
+		local height="8"
+	fi
+
+    dmenu -i -p 'Edit selected file' \
+	-nb "$background" -nf "$foreground" -sb "$color5" \
+	-sf "$background" -fn "$my_custom_ui_font" -l "$height"
+}
+
+# Capture the dmenu output
+dotsmenu_interaction="$(my_configs | my_dmenu)"
+dotsmenu_selection="$my_dots/$dotsmenu_interaction"
+
+# Open the selected file in the editor, else exit.
+# TODO add echo messages and notify-send actions.  The latter require an
+# extra dependency.  Add it to the description.
+if [ -n "$dotsmenu_interaction" ]; then
+	# TODO can these be turned into a case statement or something more
+	# elegant?
+	if [ -n "$EDITOR" ]; then
+		"$EDITOR" "$dotsmenu_selection"
+	elif [ -n "$VISUAL" ]; then
+		"$VISUAL" "$dotsmenu_selection"
+	elif [ -x /usr/bin/gvim ]; then
+		gvim "$dotsmenu_selection"
+	else
+		xdg-open "$dotsmenu_selection"
+	fi
+else
+	exit
 fi
