MAJOR CHANGES to live theme switching
1. Add `tempus`, successor to own_script_update_environment_theme.  The
   latter is now deprecated.  TEMPUS has superior performance while
   retaining feature parity.  It also has a cleaner, streamlined design.
   Furthermore, it feels more natural when used through the command
   line: `tempus classic` will switch to Tempus Classic and so on.

2. Full rewrite `tempusmenu`.  It was a complete mess as it was trying
   to interface with own_script_update_environment_theme, thus
   compounding the poor design.

3. Deprecate own_script_update_tmux_running_vim.  Use tmux_update_vim.

4. Adwaita (light,dark) is now the default GTK widget theme.  This
   removes the dependency on Materia theme.

5. Minor updates to accomodate the changes.  The most notable one is the
   removal of the check for the flatpak executable in bspwmrc.

diff --git a/bin/bin/tempusmenu b/bin/bin/tempusmenu
--- a/bin/bin/tempusmenu
+++ b/bin/bin/tempusmenu
@@ -1,174 +1,76 @@
 #!/bin/bash
 
-    # This program is free software: you can redistribute it and/or modify
-    # it under the terms of the GNU General Public License as published by
-    # the Free Software Foundation, either version 3 of the License, or
-    # (at your option) any later version.
-
-    # This program is distributed in the hope that it will be useful,
-    # but WITHOUT ANY WARRANTY; without even the implied warranty of
-    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-    # GNU General Public License for more details.
-
-    # You should have received a copy of the GNU General Public License
-    # along with this program.  If not, see <http://www.gnu.org/licenses/>.
-
-# Description
-# -----------
+# tempusmenu --- dmenu interface for `tempus`.
 #
-# This is a `dmenu` script to switch between Tempus themes on demand.
-# It parses the list of available options and presents them once
-# invoked.  The choice then becomes the input/argument of another script
-# that actually performs the operations pertaining to the complete theme
-# change.  In other words, `tempusmenu` is an interface for
-# `own_script_update_environment_theme`, both of which are part of my
-# dotfiles and are available in the "bin" directory.  See
-# https://gitlab.com/protesilaos/dotfiles (a short demo should also be
-# linked to in the README.md).
+# Provides an interactive menu from where to choose the argument that is
+# passed to the `tempus` script.  That will then live reload the session
+# to apply the new theme.  This functionality is integral to my dotfiles:
+# https://gitlab.com/protesilaos/dotfiles.
 #
-# Tempus is a collection of themes for Vim and terminal emulators that
-# is compliant *at minimum* with the WCAG AA standard for colour
-# contrast between background and foreground values.  See
-# https://protesilaos.com/tempus-themes.
+# Copyright (c) 2019 Protesilaos Stavrou <info@protesilaos.com>
 #
-# Tempus is incorporated in my dotfiles, providing for all theme-related
-# options it has ports for or can be implemented in.  The theme change
-# applies to a variety of programs, including X resources, bspwm, dunst,
-# polybar, etc.  A fully functional environment derived from my dotfiles
-# is required for this to work as intended.
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
 #
-# Last full review 2019-04-12
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# General variables
-# -----------------
 
-# We use this logic to check and then pass to the rest of the script the
-# colour values and the custom font.  If the files are not available,
-# the script exits with an error.
-source_file() {
+# Check for dependency, else exit the given function that calls this.
+_depcheck() {
+	command -v "$1" > /dev/null || { echo "Missing dependency: $1."; return 1; }
+}
+
+_depcheck dmenu
+
+_filesource() {
 	if [ -f "$1" ]; then
 		source "$1"
-	else
-		echo "ERROR: Could not find active $2"
-		echo "Aborting"
-		exit 1
 	fi
 }
 
-# Pass custom colours to the `dmenu` command.  These will style the
-# background and foreground values using shell variables.  That file is
-# used in other places as well to offer a convenient way of styling
-# multiple tools in a that is centralised and straightforward.
-my_colours="$HOME/.local/share/my_colours/active-tempus-theme.sh"
-source_file "$my_colours" 'Tempus theme'
+tempus_files="$HOME"/.local/share/my_colours
+[ -d "$tempus_files" ] || { echo "Missing path to Tempus themes."; exit 1; }
 
-# Get the system-wide custom font.  This is done with other `dmenu`
-# scripts as well to provide for an easy way to style them all at once.
-# The actual font is a `fontconfig` alias.  See my dotfiles under
-# "fontconfig".
-my_font="$HOME/.local/share/my_custom_ui_font.sh"
-source_file "$my_font" 'UI font'
+tempus_active="$tempus_files"/active-tempus-theme.sh
+tempus_shell_files="$tempus_files"/shell/
 
-# TODO use parameter expansion instead of sed
-# Array with all available tempus themes.  The `sed` command cleans up
-# the output, stripping it of surrounding text. As for `sort`, it just
-# presents the output in alphabetical order.
-tempus_themes_array=$(find "$HOME/.local/share/my_colours/shell/" -type f -printf "%f\\n" | sed -e 's/tempus_\([a-z]*\).sh/\1/g' | sort)
+dmenu_font="$HOME"/.local/share/my_custom_ui_font.sh
 
-# Functions and conditions
-# ------------------------
+_filesource "$tempus_active"
+_filesource "$dmenu_font"
 
-# This is the `dmenu` wrapper with the list of available Tempus themes.
-# Instead of offering a direct input source that yields an immediate
-# result, this command stores the user's choice as a variable which is
-# used further below.
-tempus_themes_selection() {
-    tempus_themes_choice=$(echo -e "$tempus_themes_array" | dmenu \
-    -p 'Select Tempus theme' -nb "$background" -nf "$foreground" \
-    -sb "$color5" -sf "$background" -fn "$my_custom_ui_font")
-
-
-    # This checks if the input is an empty string.  An empty string can
-    # be added by hitting the Esc key.  It fixes a critical bug where
-    # `own_script_update_environment_theme` would be executed without
-    # matching an item in the Tempus Themes array.  This would cause
-    # theme files to be replaced by an empty/invalid string.  The
-    # necessary logic has been added to that script to tackle the issue.
-    if [ -z "$tempus_themes_choice" ]; then
-        echo 'No valid selection. Exiting...'
-        exit 1
-    fi
+_themes() {
+	# The parameter expansions here keep only the theme's unique name:
+	# /path/to/tempus_classic.sh ==> classic
+	while IFS= read -r -d $'\0' line; do
+		line="${line##[a-z/_]*tempus_}"
+		printf "%s\\n" "${line%.sh}"
+	done < <(find "$tempus_shell_files" -type f -name '*.sh' -print0 | sort -z)
 }
 
-tempusmenu_confirm_input() {
-    tempus_themes_selection
-    echo "Will run desktop environment update using \"$tempus_themes_choice\""
-
-	if [ -n "$1" ]; then
-		own_script_update_environment_theme "$tempus_themes_choice" de
-	else
-		own_script_update_environment_theme "$tempus_themes_choice"
-	fi
-    exit 0
+_dmenu() {
+	dmenu -p 'Select Tempus theme' -nb "${background:-'#000000'}" -nf "${foreground:-'#ffffff'}" \
+	-sb "${color5:-'#bb6688'}" -sf "${background:-'#000000'}" -fn "${my_custom_ui_font:-'DejaVu Sans-10'}"
 }
 
-# Conditional behaviour for this script
-case "$#" in
-	0)
-        echo "There is no optional 'de' argument for tempusmenu"
-        echo "Opening dmenu interface for BSPWM environment update"
-        tempusmenu_confirm_input
-		;;
-	1)
-		if [ "$1" == "de" ]; then
-			echo "Received 'de' as an argument for tempusmenu"
-			echo "Opening dmenu interface for Desktop Environment theme update"
-			tempusmenu_confirm_input de
-		else
-			echo "ERROR. tempusmenu can only be run with 'de' as an argument"
-			echo "Your input is _$1_"
+selection="$(_themes | _dmenu)"
+
+if [ "$?" = 0 ]; then
+	case "$selection" in
+		autumn|classic|dawn|day|dusk|fugit|future|night|past|rift|spring|summer|tempest|totus|warp|winter)
+			tempus "$selection"
+			;;
+		*)
+			echo "Not a valid Tempus theme: $selection"
 			exit 1
-		fi
-		;;
-	*)
-        echo "ERROR. tempusmenu accepts one optional argument: de (for use in GNOME, MATE, Xfce)"
-        echo "You typed _$1_"
-        exit 1
-		;;
-esac
-
-# ANNEX with further explanations
-# -------------------------------
-
-# I store my colors in "$HOME/.local/share/my_colours/".  The Tempus
-# themes are at $HOME/.local/share/my_colours/shell/.
-#
-# Recall that this is a shell script that does not use the content of
-# those `*.sh`.  All we need is to extract the scheme name of each item.
-#
-# Each theme's name is prefixed with 'tempus_' and suffixed with '.sh'.
-
-# $ ls $HOME/.local/share/my_colours/shell/
-# tempus_autumn.sh   tempus_dusk.sh    tempus_past.sh    tempus_tempest.sh
-# tempus_classic.sh  tempus_fugit.sh   tempus_rift.sh    tempus_totus.sh
-# tempus_dawn.sh     tempus_future.sh  tempus_spring.sh  tempus_warp.sh
-# tempus_day.sh      tempus_night.sh   tempus_summer.sh  tempus_winter.sh
-
-# The sed regex is used to omit the prefix 'tempus_' and the suffix '.sh'.
-# $ find "$HOME/.local/share/my_colours/shell/" -type f -printf "%f\n" | sed -e 's/tempus_\([a-z]*\).sh/\1/g' | sort
-# autumn
-# classic
-# dawn
-# day
-# dusk
-# fugit
-# future
-# night
-# past
-# rift
-# spring
-# summer
-# tempest
-# totus
-# warp
-# winter
+			;;
+	esac
+fi
